config/routes.rb
Rails.application.routes.draw do
  # Topページ表示機能を実装
  get '/top' => 'homes#top'
  # 新規記事投稿機能を実装
  get 'todolists/new' => 'todolists#new'
  post '/todolists' => 'todolists#create'
  # 記事一覧表示機能を実装
  get '/todolists' => 'todolists#index'
  # 記事詳細表示機能を実装
  get '/todolists/:id' => 'todolists#show', as: 'todolist'
  # 記事編集機能を実装
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  # 記事編集後の更新を実装
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  # 記事削除機能を実装
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

  # 新規記事投稿画面
  def new
    @lists = List.new   # データベースに値を保存する処理なので、モデルを関連づける
  end


  # 作成された記事を受け取って内容をDBに保存する処理を記載
  def create
    list = List.new(list_params)  # モデルに作成された記事の内容を受け取る処理を任せる
    list.save 
    redirect_to todolist_path(list.id)
  end

  # 全データを表示する機能を実装
  def index
    @lists = List.all  # 一つ一つのデータが配列で渡される
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to todolists_path
  end

  # private => 
  private

  # 作成された記事の内容を受け取るメソッド
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>    
<% end %>

app/views/todolists/index.html.erb
<h1>記事一覧</h1>

<% @lists.each do |list|%>
    <p>タイトル</p>
    <span><%= list.title %></span>

    <%= link_to list.title, todolist_path(list.id)%>

    <%= attachment_image_tag list, :image, size: "100x100", format: 'jpeg' %>
<% end %>

app/views/todolists/new.html.erb
<h1>新規記事作成</h1>

<%= form_for(@lists, url: '/todolists') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
    <%= f.attachment_field :image %>
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/todolists/show.html.erb
<h1>記事詳細画面</h1>

<h2>タイトル</h2>
<%= @list.title %>
<h2>本文</h2>
<%= @list.body %>
<h2>画像</h2>
<%=  attachment_image_tag @list, :image,  size: "100x100", format: 'jpeg' %>

<%= link_to "編集", edit_todolist_path(@list.id) %> 
<%= link_to '削除', destroy_todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>